[package]
name = "advent2020"
version = "0.1.0"
authors = ["Adam Wick <awick@uhsure.com>"]
edition = "2018"

[dependencies]
nom = "6.0.1"
petgraph = "0.5.1"
thiserror = "1.0.22"

[profile.release]
debug = 1